let kse_listing = [
  { id: 1, name: 'ОАО Оптима Банк' },
  { id: 44, name: 'ОАО Кыргызиндустрия' },
  { id: 40, name: 'ОАО Капитал Банк Центральной Азии' },
  { id: 3, name: 'ОАО Международный аэропорт Манас' },
  { id: 4, name: 'ОАО ФинансКредитБанк' },
  { id: 5, name: 'ОАО Айыл Банк' },
  { id: 12, name: 'ОАО Электрические станции' },
  { id: 38, name: 'ОАО Национальная электрическая сеть Кыргызстана' },
  { id: 42, name: 'ЗАО UBS Transit' },
  { id: 48, name: 'ОАО Группа К51 ' },
  { id: 11, name: 'ОАО Учкун' },
  { id: 13, name: 'ОАО Кыргызтелеком' },
  { id: 24, name: 'ОАО Кыргыз Тоо-Таш' },
  { id: 16, name: 'ОАО Чакан ГЭС' },
  { id: 59, name: 'ОАО Метарайз Жапан (Metarise Japan)' },
  { id: 31, name: 'ОАО Кыргызсуудолбоор' },
  { id: 18, name: 'ОАО Тепличный' },
  { id: 19, name: 'ОАО Керемет Банк' },
  { id: 41, name: 'ОсОО Текстиль Транс' },
  { id: 20, name: 'ОсОО Первая Металлобаза' },
  { id: 21, name: 'ЗАО Кыргызский Инвестиционно-Кредитный Банк' },
  { id: 23, name: 'ОАО Кыргызалтын' },
  { id: 25, name: 'ОАО Микрофинансовая компания Салым Финанс' },
  {
    id: 26,
    name: 'ОАО Микрокредитная компания Фонд развития предпринимательства',
  },
  { id: 43, name: 'ОАО Гарантийный фонд' },
  { id: 37, name: 'ОАО Микрофинансовая компания АБН' },
  { id: 2, name: 'ОАО РСК Банк' },
  { id: 49, name: 'ЗАО Банк Азии' },
  { id: 53, name: 'ОАО Кыргызнефтегаз' },
  { id: 51, name: 'ЗАО Микрофинансовая компания Элет-Капитал' },
  { id: 52, name: 'ОсОО Стар Шина' },
  { id: 46, name: 'ОАО Государственная ипотечная компания' },
  { id: 47, name: 'ОсОО Строй дом.КГ' },
  { id: 50, name: 'ЗАО Микрофинансовая Компания ОКСУС' },
  { id: 55, name: 'OAO Либерти Эксчейндж Жапан (Liberty Exchange Japan)' },
  { id: 56, name: 'ОАО Дос - Кредобанк' },
  { id: 58, name: 'Министерство финансов Кыргызской Республики' },
];
let kse_oi = [
  { id: 2, name: 'ОАО ЦУМ-Айчурек' },
  { id: 3, name: 'ОАО ЦУМ-Холдинг' },
  { id: 35, name: 'ЗАО ЭльВест' },
  { id: 8, name: 'ОАО Кыргызавтомаш' },
  { id: 5, name: 'ОАО Капитал Банк Центральной Азии' },
  { id: 7, name: 'ОАО Оптима Банк' },
  { id: 9, name: 'ЗАО ЭкоИсламикБанк' },
  { id: 10, name: 'ОАО Чакан ГЭС' },
  { id: 11, name: 'ОАО Каракульская гидроэлектростанция' },
  { id: 12, name: 'ОАО Кыргызтелеком' },
  { id: 13, name: 'ОАО Северэлектро' },
  { id: 15, name: 'ЗАО Первая стоматология' },
  { id: 16, name: 'ОАО Учкун' },
  { id: 17, name: 'ОАО Кыргыз Тоо-Таш' },
  { id: 18, name: 'ОАО Кыргызлифт' },
  { id: 19, name: 'ЗАО Мол-Булак' },
  { id: 20, name: 'ОАО Нур' },
  { id: 21, name: 'ЗАО Уюк' },
  { id: 22, name: 'ЗАО Аман-Жол' },
  { id: 23, name: 'ЗАО Алмаз' },
  { id: 24, name: 'ЗАО Факел' },
  { id: 25, name: 'ЗАО Военно-Антоновское Спецотделение' },
  { id: 26, name: 'ОАО Курортторг Жетиген' },
  { id: 27, name: 'ОАО Кошой' },
  { id: 28, name: 'ОАО Особое конструкторское бюро Аалам' },
  { id: 29, name: 'ОАО Техсервис' },
  { id: 30, name: 'ОАО фирма Проммонтаж' },
  { id: 31, name: 'ОАО Кыргызмебель' },
  { id: 32, name: 'ОАО OREMI' },
  { id: 33, name: 'ОАО Бакай Банк' },
  { id: 34, name: 'ОАО Кыргызразнооптторг' },
  { id: 196, name: 'ОАО Кыргызский радиозавод Корпорация Ак-Марал' },
  { id: 36, name: 'ОАО Электрические станции' },
  { id: 37, name: 'ОАО Кыргызалтын' },
  { id: 38, name: 'ОАО Бишкектеплосеть' },
  { id: 39, name: 'ОАО РСК Банк' },
  { id: 40, name: 'ОАО МКК Фонд развития предпринимательства' },
  { id: 41, name: 'ОАО Кереге' },
  { id: 42, name: 'ОАО Эйр Кыргызстан' },
  { id: 102, name: 'ЗАО Каракол' },
  { id: 44, name: 'ЗАО Пансионат Солнечный берег' },
  { id: 45, name: 'ОАО КараколКПДпроектстрой' },
  { id: 46, name: 'ОАО Кыргызтемир' },
  { id: 47, name: 'ЗАО Луч' },
  { id: 48, name: 'ОАО Завод ДСМ' },
  { id: 49, name: 'ОАО Оргтехстрой' },
  { id: 50, name: 'ОАО Кыргызское' },
  { id: 51, name: 'ЗАО СУ 12' },
  { id: 52, name: 'ОАО КК Столичный' },
  { id: 53, name: 'ОАО АК Кыргызайылкомок' },
  { id: 259, name: 'ОАО Иссык-Куль-Сут' },
  { id: 54, name: 'ОАО КыргызВНИПИЭнергопром' },
  { id: 186, name: 'ОсОО Grand House (Гранд Хаус)' },
  { id: 187, name: 'ОсОО Первая Металлобаза' },
  { id: 56, name: 'ОАО Жаштыкинвест' },
  { id: 57, name: 'ОАО Элесинвест' },
  { id: 58, name: 'ОАО Чуй Унаа Ишканасы' },
  { id: 59, name: 'ОАО гостиница Достук' },
  { id: 60, name: 'ОАО Корпорация Машиностроение' },
  { id: 61, name: 'ОАО Автодорснаб' },
  { id: 62, name: 'ОАО Жумгалсуукурулуш' },
  { id: 63, name: 'ОАО Бишкекский машиностроительный завод' },
  { id: 64, name: 'ОАО Завод сверл' },
  { id: 65, name: 'ОАО Кыргызэлектросетьстрой' },
  { id: 66, name: 'ОАО Полибетон' },
  { id: 67, name: 'ОАО Чельпек' },
  { id: 68, name: 'ОАО Жемиш' },
  { id: 69, name: 'ОАО Автотранспортное предприятие №6' },
  { id: 70, name: 'ОАО Айыл Банк' },
  { id: 71, name: 'ОАО Golden Sun (Голден Сан)' },
  { id: 72, name: 'ОАО Ысык-Кол Фармация' },
  { id: 73, name: 'ОАО Независимая хлебная инспекция' },
  { id: 74, name: 'ОАО Булочно-кондитерский комбинат' },
  { id: 75, name: 'ОАО Коммерческий банк Кыргызстан' },
  { id: 76, name: 'ОАО Global Invest (Глобал Инвест)' },
  { id: 77, name: 'ОАО Бишкек-Нан им.Шеримкулова К.Ш.' },
  { id: 78, name: 'ОАО Страховая компания Ак-Жол' },
  { id: 79, name: 'ОАО Тепличный' },
  { id: 80, name: 'ОАО Линия Права Уран' },
  { id: 81, name: 'ОАО Оргприминструмент' },
  { id: 82, name: 'ЗАО Стройфирма Иссык-Куль' },
  { id: 83, name: 'ОАО Домостроительная корпорация Азат' },
  { id: 84, name: 'ЗАО Азаттык' },
  { id: 85, name: 'ОАО Айгул' },
  { id: 87, name: 'ОАО Кыргызсуудолбоор' },
  { id: 88, name: 'ОАО Ак-Тилек' },
  { id: 89, name: 'ОАО Тулпар' },
  { id: 90, name: 'ОАО ПТО Кыргызторгтехника' },
  { id: 91, name: 'ОАО ПСФ Бишкеккурулуш' },
  { id: 92, name: 'ОАО Реемтсма-Кыргызстан' },
  { id: 93, name: 'ОАО Битекс Компани' },
  { id: 94, name: 'ОАО Кыргызинвест' },
  { id: 95, name: 'ОАО фирма Ак-Кула' },
  { id: 96, name: 'ЗАО Иссык-Кульское предприятие по поставкам продукции' },
  { id: 97, name: 'ОАО Бишкекское грузовое автотранспортное предприятие' },
  { id: 98, name: 'ОАО Вентра' },
  { id: 99, name: 'ОАО Кыргызхимторг' },
  { id: 100, name: 'ОАО Дитис' },
  { id: 101, name: 'ОАО Азия Агроресурс' },
  { id: 103, name: 'ОАО Ала-Тоо' },
  { id: 104, name: 'ОАО Арча' },
  { id: 105, name: 'ОАО Промпроект' },
  { id: 106, name: 'ЗАО Кантская МПМК-2' },
  { id: 107, name: 'ОАО Аэродромдорстрой' },
  { id: 108, name: 'ОАО Талас Басмаканасы' },
  { id: 109, name: 'ЗАО Бишкекстройматериалы' },
  { id: 110, name: 'ЗАО Силикат' },
  { id: 111, name: 'ОАО фирма Сантехма' },
  { id: 112, name: 'ОАО Уста' },
  { id: 113, name: 'ЗАО Азия-Вест-Бишкекский Торговый Дом' },
  { id: 114, name: 'ОАО Кыргызгаз' },
  { id: 115, name: 'ОАО Нарынспецгидроэнергомонтаж' },
  { id: 116, name: 'ОАО Кыргыз ГИИЗ' },
  { id: 117, name: 'ОАО Ысык-Кол Суу Курулуш' },
  { id: 118, name: 'ОАО Каинды Эт Комбинаты' },
  { id: 119, name: 'ОАО Кантская ПМК' },
  { id: 120, name: 'ОАО ФинансКредитБанк' },
  { id: 121, name: 'ОАО Кеминский электротехнический завод' },
  { id: 122, name: 'ОАО Апросах' },
  { id: 124, name: 'ОАО Кантский хлебозавод' },
  { id: 125, name: 'ОАО Опытное кожевенно-кожгалантерейное объединение' },
  { id: 126, name: 'ОАО KDM TV (КиДиЭм ТиВи)' },
  { id: 127, name: 'ОАО Эмерек' },
  { id: 128, name: 'ОАО Медиа Форум' },
  { id: 129, name: 'ОАО Халык Банк Кыргызстан' },
  { id: 130, name: 'ОАО ВТИ-Сервис' },
  { id: 131, name: 'ОАО Асфальтобетон' },
  { id: 132, name: 'ОАО Международный аэропорт Манас' },
  { id: 133, name: 'ОАО Шумкар-ЫККФ' },
  { id: 134, name: 'ОАО Балыкчы ПАТП' },
  { id: 135, name: 'ОАО Бишкексут' },
  { id: 136, name: 'ОАО Домостроитель' },
  { id: 137, name: 'ОАО Проммаркет' },
  { id: 138, name: 'ЗАО Бермет' },
  { id: 139, name: 'ОАО Токмок ПАТП' },
  { id: 140, name: 'ОАО Касиет' },
  { id: 141, name: 'ОАО Автоуслуги' },
  { id: 142, name: 'ОАО Ак-Куу' },
  { id: 143, name: 'ОАО КыргызАВТОВАЗ' },
  { id: 144, name: 'ОАО Нарынжолкурулуш' },
  { id: 145, name: 'ОАО Жибек-Жол' },
  { id: 146, name: 'ОАО Теским' },
  { id: 147, name: 'ОАО Ак-Марал' },
  { id: 148, name: 'ОАО Сокулукский ККП' },
  { id: 149, name: 'ОАО Кыргыз-Таш' },
  { id: 150, name: 'ОАО ТАК' },
  { id: 151, name: 'ОАО Автосборочный завод' },
  { id: 152, name: 'ОАО ДОЗ №3' },
  { id: 153, name: 'ОАО Кыргызкоммерцбанк' },
  { id: 154, name: 'ОАО Евразийский Сберегательный Банк' },
  { id: 155, name: 'ОАО Кара-Балтинский комбинат коммунальных предприятий' },
  { id: 156, name: 'ОАО Конструкторское Бюро Инструмента' },
  { id: 157, name: 'ОАО Logic (Лоджик)' },
  { id: 158, name: 'ОАО Кыргызэнергострой' },
  { id: 159, name: 'ОАО Бишкекремстрой' },
  { id: 160, name: 'ОАО Инвестиционная Группа Алем Билдинг' },
  { id: 161, name: 'ОАО Кыргызбакалея' },
  { id: 162, name: 'ОАО Каинды-Кант' },
  { id: 163, name: 'ОАО Электротехник' },
  { id: 164, name: 'ЗАО Микрокредитная компания ТРАСТ-ЮНИОН' },
  { id: 165, name: 'ОАО Арстанбек' },
  { id: 166, name: 'ОАО Спецмонтажавтоматика' },
  { id: 167, name: 'ЗАО FORIS TELECOM KG (ФОРИС ТЕЛЕКОМ КейДжи)' },
  { id: 168, name: 'ОАО Тоо-Тек' },
  { id: 169, name: 'ОАО Карабалтинская типография' },
  { id: 170, name: 'ОАО Сейил' },
  { id: 171, name: 'ЗАО P&Co Инвест' },
  { id: 172, name: 'ОАО Каиндинский кабельный завод' },
  { id: 173, name: 'ОАО Кантская типография' },
  { id: 174, name: 'ОАО Кыргыз Долбоор' },
  { id: 175, name: 'ОАО Завод Айнур' },
  { id: 176, name: 'ОАО Керемет Банк' },
  { id: 177, name: 'ОАО СПАБ' },
  { id: 178, name: 'ОАО Финансовая Компания Кредитных Союзов' },
  { id: 179, name: 'ОАО Востокэлектро' },
  { id: 180, name: 'ОАО Сокулукжолкурулуш' },
  { id: 201, name: 'ОАО Арашан' },
  { id: 182, name: 'ОАО Страховая компания АЮ Гарант' },
  { id: 183, name: 'ОАО Проектный институт Кыргызгипрострой' },
  { id: 184, name: 'ОАО Улан' },
  { id: 185, name: 'ОАО Чуйбатышкурулуш' },
  { id: 188, name: 'ОсОО Компания Росказмет' },
  { id: 189, name: 'ЗАО Кыргызский Инвестиционно-Кредитный Банк' },
  { id: 190, name: 'ЗАО Шоро' },
  { id: 191, name: 'ОАО Ош Жибек' },
  { id: 192, name: 'ОАО МФК Салым Финанс' },
  { id: 193, name: 'ОАО Бизнес центр Ай-Пери' },
  { id: 194, name: 'ОАО Аптека №155' },
  { id: 195, name: 'ОсОО Кантское РПО по МЭ' },
  { id: 197, name: 'ОАО Эркин-Тоо' },
  { id: 198, name: 'ОсОО АЮ' },
  { id: 199, name: 'ЗАО Ысык-Атинский завод керамических изделий' },
  { id: 200, name: 'ОАО Дос-Кредобанк' },
  { id: 202, name: 'ОАО Кантский цементный завод' },
  { id: 203, name: 'ОАО Арпа им. Насыркула Урманбетова' },
  { id: 204, name: '' },
  { id: 205, name: 'ОАО Южремстрой' },
  { id: 206, name: 'ОАО Национальная электрическая сеть Кыргызстана' },
  { id: 207, name: 'ОАО Сорок лет Октября' },
  { id: 208, name: 'ОАО Микрофинансовая компания АБН' },
  { id: 209, name: 'ОАО СУ-93' },
  { id: 210, name: 'ОАО Ак-Орго' },
  { id: 211, name: 'ОАО Аламудунский опытный ремонтно-механический завод' },
  { id: 212, name: 'ОАО Ак-Сут' },
  { id: 213, name: 'ОАО Талас Алтын' },
  { id: 214, name: 'ОАО АИФ Береке-Инвест' },
  { id: 215, name: 'ОАО Аламудунская ПМК' },
  { id: 216, name: 'ОАО Инвестиционный Банк Чанг Ан' },
  { id: 217, name: 'ОАО Ак-Таш' },
  { id: 218, name: 'ОАО Герои Панфиловцы' },
  { id: 219, name: 'ОАО Акжолтой' },
  { id: 220, name: 'ОАО Агроснаб' },
  { id: 221, name: 'ОАО Линолеум' },
  { id: 222, name: 'ОАО Сон-Куль' },
  { id: 223, name: 'ОАО Завод ЖБИ' },
  { id: 224, name: 'ОАО Салам' },
  { id: 225, name: 'ОТКАО Ак-Жол' },
  { id: 226, name: 'ОАО Торговый дом Мин Туркун' },
  { id: 227, name: 'ОсОО АЮ Курулуш' },
  { id: 228, name: 'ОАО Жалалабатэлектро' },
  { id: 229, name: 'ОАО Фармация' },
  { id: 230, name: 'ОАО Ошское ПНУ' },
  { id: 232, name: 'ОАО Ак-Суйское АТП' },
  { id: 233, name: 'ОАО Кадам' },
  {
    id: 261,
    name: 'ОАО Центр проектного финансирования регионального развития',
  },
  {
    id: 275,
    name: 'ОАО Жилищно-сберегательная кредитная компания Народная жилищная компания',
  },
  { id: 234, name: 'ОАО Кыргызский химико-металлургический завод' },
  { id: 235, name: 'ОАО Райдер Ассошиэйтс Лимитед' },
  { id: 236, name: 'ОАО Ошэлектро' },
  { id: 237, name: 'ОАО Гарантийный фонд' },
  { id: 238, name: 'ОАО УБГ Инвест' },
  { id: 240, name: 'ОАО Машиноиспытательная станция' },
  {
    id: 239,
    name: 'ОАО Республиканское производственное объединение радиорелейных магистралей, телевидения и радиовещания',
  },
  { id: 283, name: 'ОАО Кыргызиндустрия' },
  { id: 241, name: 'ОАО Жети-Огуз' },
  { id: 242, name: 'ОАО Государственная Страховая Организация' },
  { id: 243, name: 'ОАО Железобетон' },
  { id: 244, name: 'ОАО Акбулак' },
  { id: 245, name: 'ОАО Искра Азии' },
  { id: 246, name: 'ЗАО Бессер-Центральная Азия' },
  { id: 247, name: 'ЗАО МФК Алма-Кредит' },
  { id: 248, name: 'ОАО Государственная ипотечная компания' },
  { id: 249, name: 'ОАО ТНК Дастан' },
  { id: 250, name: 'ОАО Группа К51' },
  { id: 251, name: 'ЗАО Строительное управление №4' },
  { id: 252, name: 'ОсОО Ихсан-Орикс' },
  { id: 253, name: 'ОАО Шоппинг онлайн центр' },
  { id: 254, name: 'ОАО Евразийская валютно-фондовая инвестиционная биржа' },
  { id: 257, name: 'ОАО УСМ-4' },
  {
    id: 255,
    name: 'ЗАО Универсальная товарно-сырьевая биржа социального и инновационного развития',
  },
  { id: 256, name: 'ОАО Адилет' },
  { id: 272, name: 'ОсОО Баркад' },
  { id: 260, name: 'ОАО Авто-Жол' },
  { id: 270, name: 'ОАО Чолпон-Ата ПАТП' },
  { id: 262, name: 'ОАО Кыргызский Энергетический Расчетный Центр' },
  { id: 263, name: 'ОАО Апар Сервис' },
  { id: 264, name: 'ЗАО НПФ Дордой Салым' },
  { id: 265, name: 'ОАО НПФ Кыргызстан' },
  { id: 266, name: 'ОАО Ала-Тоо Инвест' },
  { id: 267, name: 'ОАО Тест (ЗАО КФБ)' },
  { id: 268, name: 'ОАО Кыргыз Винд Систем' },
  { id: 269, name: 'ОАО Банк Бай-Тушум' },
  { id: 271, name: 'ОАО Ками Моторс' },
  { id: 273, name: 'ОАО Келдике' },
  { id: 274, name: 'ОАО Авторемонтный завод' },
  { id: 279, name: 'ОсОО Текстиль Транс' },
  { id: 276, name: 'ОАО РК Аманбанк' },
  { id: 293, name: 'ЗАО Микрофинансовая компания Элет-Капитал' },
  { id: 277, name: 'ОАО Каухар Таш' },
  { id: 278, name: 'ОАО Шатер' },
  { id: 281, name: 'ЗАО UBS Transit' },
  { id: 282, name: 'ОАО МФК ИнвесКор СА' },
  {
    id: 284,
    name: 'ОАО Национальная холдинговая компания  Наследие великих кочевников',
  },
  {
    id: 285,
    name: 'ОАО Фонд поддержки развития туризма в Кыргызской Республике',
  },
  { id: 286, name: 'ЗАО Банк Азии' },
  { id: 287, name: 'ОсОО Строй дом.КГ' },
  { id: 288, name: 'ЗАО Компания Аэростар' },
  { id: 289, name: 'ОАО Кыргызтрансавто' },
  { id: 290, name: 'ЗАО Микрофинансовая компания ОКСУС' },
  { id: 291, name: 'ОАО Ашар Капитал' },
  { id: 292, name: 'ЗАО Технологическая компания Иссык-Куль' },
  { id: 294, name: 'ОсОО Стар Шина' },
  { id: 295, name: 'ОАО Кыргыз почтасы' },
  { id: 296, name: 'ОАО Государственный банк развития Кыргызской Республики' },
  { id: 299, name: 'ОАО Ашар Инвест' },
  { id: 300, name: 'ОАО Ашар Девелопмент' },
  { id: 301, name: 'ОАО Кыргызнефтегаз' },
  { id: 302, name: 'ОАО Меркатор' },
  { id: 303, name: 'OAO Либерти Эксчейндж Жапан (Liberty Exchange Japan)' },
];
const data = [
  { id: 1, oi_company_id: 13, kse_company_id: 20, type: 'listing' },
  { id: 2, oi_company_id: 178, kse_company_id: 18, type: 'listing' },
  { id: 3, oi_company_id: 35, kse_company_id: 37, type: 'listing' },
  { id: 4, oi_company_id: 51, kse_company_id: 21, type: 'listing' },
  { id: 5, oi_company_id: 73, kse_company_id: 23, type: 'listing' },
  { id: 6, oi_company_id: 172, kse_company_id: 5, type: 'listing' },
  { id: 7, oi_company_id: 171, kse_company_id: 4, type: 'listing' },
  { id: 8, oi_company_id: 240, kse_company_id: 55, type: 'listing' },
  { id: 9, oi_company_id: 138, kse_company_id: 24, type: 'listing' },
  { id: 10, oi_company_id: 122, kse_company_id: 20, type: 'listing' },
  { id: 11, oi_company_id: 218, kse_company_id: 38, type: 'listing' },
  { id: 12, oi_company_id: 176, kse_company_id: 11, type: 'listing' },
  { id: 13, oi_company_id: 168, kse_company_id: 1, type: 'listing' },
  { id: 14, oi_company_id: 235, kse_company_id: 55, type: 'listing' },
  { id: 15, oi_company_id: 102, kse_company_id: 37, type: 'listing' },
  { id: 16, oi_company_id: 169, kse_company_id: 2, type: 'listing' },
  { id: 17, oi_company_id: 219, kse_company_id: 42, type: 'listing' },
  { id: 18, oi_company_id: 162, kse_company_id: 43, type: 'listing' },
  { id: 19, oi_company_id: 177, kse_company_id: 13, type: 'listing' },
  { id: 20, oi_company_id: 182, kse_company_id: 31, type: 'listing' },
  { id: 21, oi_company_id: 224, kse_company_id: 49, type: 'listing' },
  { id: 22, oi_company_id: 234, kse_company_id: 49, type: 'listing' },
  { id: 23, oi_company_id: 174, kse_company_id: 46, type: 'listing' },
  { id: 24, oi_company_id: 223, kse_company_id: 50, type: 'listing' },
  { id: 25, oi_company_id: 173, kse_company_id: 12, type: 'listing' },
  { id: 26, oi_company_id: 170, kse_company_id: 3, type: 'listing' },
  { id: 27, oi_company_id: 238, kse_company_id: 53, type: 'listing' },
  { id: 28, oi_company_id: 220, kse_company_id: 44, type: 'listing' },
  { id: 29, oi_company_id: 125, kse_company_id: 16, type: 'listing' },
  { id: 30, oi_company_id: 228, kse_company_id: 51, type: 'listing' },
  { id: 31, oi_company_id: 227, kse_company_id: 47, type: 'listing' },
  { id: 32, oi_company_id: 217, kse_company_id: 40, type: 'listing' },
  { id: 33, oi_company_id: 75, kse_company_id: 48, type: 'listing' },
  { id: 34, oi_company_id: 179, kse_company_id: 19, type: 'listing' },
  { id: 35, oi_company_id: 226, kse_company_id: 41, type: 'listing' },
  { id: 36, oi_company_id: 107, kse_company_id: 25, type: 'listing' },
  { id: 37, oi_company_id: 183, kse_company_id: 26, type: 'listing' },
  { id: 38, oi_company_id: 233, kse_company_id: 56, type: 'listing' },
  { id: 39, oi_company_id: 12, kse_company_id: 58, type: 'listing' },
  { id: 40, oi_company_id: 3, kse_company_id: 188, type: 'oi' },
  { id: 41, oi_company_id: 4, kse_company_id: 147, type: 'oi' },
  { id: 42, oi_company_id: 21, kse_company_id: 3, type: 'oi' },
  { id: 43, oi_company_id: 14, kse_company_id: 28, type: 'oi' },
  { id: 44, oi_company_id: 13, kse_company_id: 187, type: 'oi' },
  { id: 45, oi_company_id: 17, kse_company_id: 52, type: 'oi' },
  { id: 46, oi_company_id: 18, kse_company_id: 107, type: 'oi' },
  { id: 47, oi_company_id: 22, kse_company_id: 193, type: 'oi' },
  { id: 48, oi_company_id: 6, kse_company_id: 154, type: 'oi' },
  { id: 49, oi_company_id: 188, kse_company_id: 271, type: 'oi' },
  { id: 50, oi_company_id: 9, kse_company_id: 61, type: 'oi' },
  { id: 51, oi_company_id: 193, kse_company_id: 272, type: 'oi' },
  { id: 52, oi_company_id: 194, kse_company_id: 74, type: 'oi' },
  { id: 53, oi_company_id: 15, kse_company_id: 185, type: 'oi' },
  { id: 54, oi_company_id: 196, kse_company_id: 276, type: 'oi' },
  { id: 55, oi_company_id: 189, kse_company_id: 119, type: 'oi' },
  { id: 56, oi_company_id: 186, kse_company_id: 270, type: 'oi' },
  { id: 57, oi_company_id: 178, kse_company_id: 79, type: 'oi' },
  { id: 58, oi_company_id: 28, kse_company_id: 183, type: 'oi' },
  { id: 59, oi_company_id: 33, kse_company_id: 152, type: 'oi' },
  { id: 60, oi_company_id: 35, kse_company_id: 208, type: 'oi' },
  { id: 61, oi_company_id: 42, kse_company_id: 33, type: 'oi' },
  { id: 62, oi_company_id: 34, kse_company_id: 139, type: 'oi' },
  { id: 63, oi_company_id: 40, kse_company_id: 122, type: 'oi' },
  { id: 64, oi_company_id: 43, kse_company_id: 194, type: 'oi' },
  { id: 65, oi_company_id: 44, kse_company_id: 224, type: 'oi' },
  { id: 66, oi_company_id: 47, kse_company_id: 177, type: 'oi' },
  { id: 67, oi_company_id: 30, kse_company_id: 84, type: 'oi' },
  { id: 68, oi_company_id: 39, kse_company_id: 175, type: 'oi' },
  { id: 69, oi_company_id: 29, kse_company_id: 2, type: 'oi' },
  { id: 70, oi_company_id: 32, kse_company_id: 59, type: 'oi' },
  { id: 71, oi_company_id: 27, kse_company_id: 116, type: 'oi' },
  { id: 72, oi_company_id: 46, kse_company_id: 27, type: 'oi' },
  { id: 73, oi_company_id: 41, kse_company_id: 161, type: 'oi' },
  { id: 74, oi_company_id: 45, kse_company_id: 93, type: 'oi' },
  { id: 75, oi_company_id: 49, kse_company_id: 142, type: 'oi' },
  { id: 76, oi_company_id: 56, kse_company_id: 90, type: 'oi' },
  { id: 77, oi_company_id: 59, kse_company_id: 224, type: 'oi' },
  { id: 78, oi_company_id: 74, kse_company_id: 73, type: 'oi' },
  { id: 79, oi_company_id: 239, kse_company_id: 302, type: 'oi' },
  { id: 80, oi_company_id: 51, kse_company_id: 189, type: 'oi' },
  { id: 81, oi_company_id: 231, kse_company_id: 295, type: 'oi' },
  { id: 82, oi_company_id: 61, kse_company_id: 145, type: 'oi' },
  { id: 83, oi_company_id: 79, kse_company_id: 166, type: 'oi' },
  { id: 84, oi_company_id: 52, kse_company_id: 38, type: 'oi' },
  { id: 85, oi_company_id: 78, kse_company_id: 223, type: 'oi' },
  { id: 86, oi_company_id: 65, kse_company_id: 143, type: 'oi' },
  { id: 87, oi_company_id: 71, kse_company_id: 83, type: 'oi' },
  { id: 88, oi_company_id: 73, kse_company_id: 37, type: 'oi' },
  { id: 89, oi_company_id: 55, kse_company_id: 240, type: 'oi' },
  { id: 90, oi_company_id: 57, kse_company_id: 105, type: 'oi' },
  { id: 91, oi_company_id: 68, kse_company_id: 127, type: 'oi' },
  { id: 92, oi_company_id: 180, kse_company_id: 198, type: 'oi' },
  { id: 93, oi_company_id: 183, kse_company_id: 40, type: 'oi' },
  { id: 94, oi_company_id: 89, kse_company_id: 90, type: 'oi' },
  { id: 95, oi_company_id: 172, kse_company_id: 70, type: 'oi' },
  { id: 96, oi_company_id: 11, kse_company_id: 64, type: 'oi' },
  { id: 97, oi_company_id: 48, kse_company_id: 215, type: 'oi' },
  { id: 98, oi_company_id: 5, kse_company_id: 153, type: 'oi' },
  { id: 99, oi_company_id: 70, kse_company_id: 162, type: 'oi' },
  { id: 100, oi_company_id: 171, kse_company_id: 120, type: 'oi' },
  { id: 101, oi_company_id: 31, kse_company_id: 225, type: 'oi' },
  { id: 102, oi_company_id: 20, kse_company_id: 111, type: 'oi' },
  { id: 103, oi_company_id: 63, kse_company_id: 135, type: 'oi' },
  { id: 104, oi_company_id: 232, kse_company_id: 296, type: 'oi' },
  { id: 105, oi_company_id: 50, kse_company_id: 62, type: 'oi' },
  { id: 106, oi_company_id: 104, kse_company_id: 147, type: 'oi' },
  { id: 107, oi_company_id: 67, kse_company_id: 72, type: 'oi' },
  { id: 108, oi_company_id: 117, kse_company_id: 48, type: 'oi' },
  { id: 109, oi_company_id: 156, kse_company_id: 196, type: 'oi' },
  { id: 110, oi_company_id: 106, kse_company_id: 29, type: 'oi' },
  { id: 111, oi_company_id: 113, kse_company_id: 149, type: 'oi' },
  { id: 112, oi_company_id: 157, kse_company_id: 58, type: 'oi' },
  { id: 113, oi_company_id: 121, kse_company_id: 221, type: 'oi' },
  { id: 114, oi_company_id: 109, kse_company_id: 177, type: 'oi' },
  { id: 115, oi_company_id: 110, kse_company_id: 166, type: 'oi' },
  { id: 116, oi_company_id: 240, kse_company_id: 303, type: 'oi' },
  { id: 117, oi_company_id: 112, kse_company_id: 94, type: 'oi' },
  { id: 118, oi_company_id: 111, kse_company_id: 121, type: 'oi' },
  { id: 119, oi_company_id: 115, kse_company_id: 131, type: 'oi' },
  { id: 120, oi_company_id: 114, kse_company_id: 26, type: 'oi' },
  { id: 121, oi_company_id: 200, kse_company_id: 242, type: 'oi' },
  { id: 122, oi_company_id: 155, kse_company_id: 178, type: 'oi' },
  { id: 123, oi_company_id: 108, kse_company_id: 224, type: 'oi' },
  { id: 124, oi_company_id: 107, kse_company_id: 192, type: 'oi' },
  { id: 125, oi_company_id: 60, kse_company_id: 67, type: 'oi' },
  { id: 126, oi_company_id: 158, kse_company_id: 174, type: 'oi' },
  { id: 127, oi_company_id: 124, kse_company_id: 151, type: 'oi' },
  { id: 128, oi_company_id: 130, kse_company_id: 232, type: 'oi' },
  { id: 129, oi_company_id: 137, kse_company_id: 222, type: 'oi' },
  { id: 130, oi_company_id: 138, kse_company_id: 17, type: 'oi' },
  { id: 131, oi_company_id: 122, kse_company_id: 187, type: 'oi' },
  { id: 132, oi_company_id: 218, kse_company_id: 206, type: 'oi' },
  { id: 133, oi_company_id: 127, kse_company_id: 210, type: 'oi' },
  { id: 134, oi_company_id: 128, kse_company_id: 103, type: 'oi' },
  { id: 135, oi_company_id: 142, kse_company_id: 148, type: 'oi' },
  { id: 136, oi_company_id: 131, kse_company_id: 60, type: 'oi' },
  { id: 137, oi_company_id: 134, kse_company_id: 118, type: 'oi' },
  { id: 138, oi_company_id: 120, kse_company_id: 49, type: 'oi' },
  { id: 139, oi_company_id: 123, kse_company_id: 252, type: 'oi' },
  { id: 140, oi_company_id: 153, kse_company_id: 134, type: 'oi' },
  { id: 141, oi_company_id: 126, kse_company_id: 112, type: 'oi' },
  { id: 142, oi_company_id: 136, kse_company_id: 108, type: 'oi' },
  { id: 143, oi_company_id: 148, kse_company_id: 128, type: 'oi' },
  { id: 144, oi_company_id: 64, kse_company_id: 85, type: 'oi' },
  { id: 145, oi_company_id: 176, kse_company_id: 16, type: 'oi' },
  { id: 146, oi_company_id: 164, kse_company_id: 203, type: 'oi' },
  { id: 147, oi_company_id: 58, kse_company_id: 212, type: 'oi' },
  { id: 148, oi_company_id: 168, kse_company_id: 7, type: 'oi' },
  { id: 149, oi_company_id: 235, kse_company_id: 303, type: 'oi' },
  { id: 150, oi_company_id: 102, kse_company_id: 208, type: 'oi' },
  { id: 151, oi_company_id: 169, kse_company_id: 39, type: 'oi' },
  { id: 152, oi_company_id: 118, kse_company_id: 31, type: 'oi' },
  { id: 153, oi_company_id: 219, kse_company_id: 281, type: 'oi' },
  { id: 154, oi_company_id: 184, kse_company_id: 83, type: 'oi' },
  { id: 155, oi_company_id: 139, kse_company_id: 170, type: 'oi' },
  { id: 156, oi_company_id: 159, kse_company_id: 50, type: 'oi' },
  { id: 157, oi_company_id: 162, kse_company_id: 237, type: 'oi' },
  { id: 158, oi_company_id: 146, kse_company_id: 266, type: 'oi' },
  { id: 159, oi_company_id: 221, kse_company_id: 285, type: 'oi' },
  { id: 160, oi_company_id: 141, kse_company_id: 265, type: 'oi' },
  { id: 161, oi_company_id: 144, kse_company_id: 63, type: 'oi' },
  { id: 162, oi_company_id: 161, kse_company_id: 155, type: 'oi' },
  { id: 163, oi_company_id: 145, kse_company_id: 202, type: 'oi' },
  { id: 164, oi_company_id: 165, kse_company_id: 249, type: 'oi' },
  { id: 165, oi_company_id: 166, kse_company_id: 184, type: 'oi' },
  { id: 166, oi_company_id: 167, kse_company_id: 253, type: 'oi' },
  { id: 167, oi_company_id: 160, kse_company_id: 89, type: 'oi' },
  { id: 168, oi_company_id: 175, kse_company_id: 13, type: 'oi' },
  { id: 169, oi_company_id: 150, kse_company_id: 57, type: 'oi' },
  { id: 170, oi_company_id: 143, kse_company_id: 169, type: 'oi' },
  { id: 171, oi_company_id: 1, kse_company_id: 263, type: 'oi' },
  { id: 172, oi_company_id: 154, kse_company_id: 126, type: 'oi' },
  { id: 173, oi_company_id: 187, kse_company_id: 129, type: 'oi' },
  { id: 174, oi_company_id: 152, kse_company_id: 75, type: 'oi' },
  { id: 175, oi_company_id: 177, kse_company_id: 12, type: 'oi' },
  { id: 176, oi_company_id: 236, kse_company_id: 300, type: 'oi' },
  { id: 177, oi_company_id: 37, kse_company_id: 173, type: 'oi' },
  { id: 178, oi_company_id: 36, kse_company_id: 54, type: 'oi' },
  { id: 179, oi_company_id: 185, kse_company_id: 268, type: 'oi' },
  { id: 180, oi_company_id: 135, kse_company_id: 141, type: 'oi' },
  { id: 181, oi_company_id: 132, kse_company_id: 125, type: 'oi' },
  { id: 182, oi_company_id: 151, kse_company_id: 214, type: 'oi' },
  { id: 183, oi_company_id: 197, kse_company_id: 201, type: 'oi' },
  { id: 184, oi_company_id: 182, kse_company_id: 87, type: 'oi' },
  { id: 185, oi_company_id: 53, kse_company_id: 91, type: 'oi' },
  { id: 186, oi_company_id: 224, kse_company_id: 286, type: 'oi' },
  { id: 187, oi_company_id: 237, kse_company_id: 299, type: 'oi' },
  { id: 188, oi_company_id: 19, kse_company_id: 71, type: 'oi' },
  { id: 189, oi_company_id: 38, kse_company_id: 30, type: 'oi' },
  { id: 190, oi_company_id: 103, kse_company_id: 122, type: 'oi' },
  { id: 191, oi_company_id: 225, kse_company_id: 291, type: 'oi' },
  { id: 192, oi_company_id: 190, kse_company_id: 269, type: 'oi' },
  { id: 193, oi_company_id: 24, kse_company_id: 158, type: 'oi' },
  { id: 194, oi_company_id: 25, kse_company_id: 76, type: 'oi' },
  { id: 195, oi_company_id: 105, kse_company_id: 262, type: 'oi' },
  { id: 196, oi_company_id: 16, kse_company_id: 157, type: 'oi' },
  { id: 197, oi_company_id: 133, kse_company_id: 165, type: 'oi' },
  { id: 198, oi_company_id: 234, kse_company_id: 286, type: 'oi' },
  { id: 199, oi_company_id: 76, kse_company_id: 53, type: 'oi' },
  { id: 200, oi_company_id: 229, kse_company_id: 219, type: 'oi' },
  { id: 201, oi_company_id: 23, kse_company_id: 8, type: 'oi' },
  { id: 202, oi_company_id: 75, kse_company_id: 250, type: 'oi' },
  { id: 203, oi_company_id: 69, kse_company_id: 136, type: 'oi' },
  { id: 204, oi_company_id: 26, kse_company_id: 77, type: 'oi' },
  { id: 205, oi_company_id: 174, kse_company_id: 248, type: 'oi' },
  { id: 206, oi_company_id: 223, kse_company_id: 290, type: 'oi' },
  { id: 207, oi_company_id: 202, kse_company_id: 278, type: 'oi' },
  { id: 208, oi_company_id: 173, kse_company_id: 36, type: 'oi' },
  { id: 209, oi_company_id: 72, kse_company_id: 146, type: 'oi' },
  { id: 210, oi_company_id: 170, kse_company_id: 132, type: 'oi' },
  { id: 211, oi_company_id: 238, kse_company_id: 301, type: 'oi' },
  { id: 212, oi_company_id: 220, kse_company_id: 283, type: 'oi' },
  { id: 213, oi_company_id: 125, kse_company_id: 10, type: 'oi' },
  { id: 214, oi_company_id: 195, kse_company_id: 275, type: 'oi' },
  { id: 215, oi_company_id: 228, kse_company_id: 293, type: 'oi' },
  { id: 216, oi_company_id: 129, kse_company_id: 66, type: 'oi' },
  { id: 217, oi_company_id: 227, kse_company_id: 287, type: 'oi' },
  { id: 218, oi_company_id: 10, kse_company_id: 267, type: 'oi' },
  { id: 219, oi_company_id: 54, kse_company_id: 246, type: 'oi' },
  { id: 220, oi_company_id: 179, kse_company_id: 176, type: 'oi' },
  { id: 221, oi_company_id: 62, kse_company_id: 176, type: 'oi' },
  { id: 222, oi_company_id: 217, kse_company_id: 5, type: 'oi' },
  { id: 223, oi_company_id: 233, kse_company_id: 200, type: 'oi' },
  { id: 224, oi_company_id: 181, kse_company_id: 226, type: 'oi' },
  { id: 225, oi_company_id: 149, kse_company_id: 56, type: 'oi' },
  { id: 226, oi_company_id: 163, kse_company_id: 239, type: 'oi' },
  { id: 227, oi_company_id: 199, kse_company_id: 241, type: 'oi' },
  { id: 228, oi_company_id: 130, kse_company_id: 130, type: 'oi' },
  { id: 229, oi_company_id: 226, kse_company_id: 279, type: 'oi' },
  { id: 230, oi_company_id: 140, kse_company_id: null, type: 'oi' },
];
